[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_pgsql", "php84Extensions.mbstring", "php84Extensions.curl"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080"